[tasks.gen-vmlinux]
run = "bpftool btf dump file /sys/kernel/btf/vmlinux format c > src/vmlinux.h"

[tasks.gen-http-response]
run = "xh http://www.example.com -p hb -o ./scripts/http_response.txt"

[tasks.gen-packet]
run = "uv run scripts/gen-packet.py"

[tasks.build-bpf]
depends = ["gen-vmlinux"]
sources = ["src/parse.bpf.c", "src/vmlinux.h"]
run = "clang -O1 -g -Wall -target bpf -c src/parse.bpf.c -o bin/parse.bpf.o -Isrc"

[tasks.tearup]
alias = "tup"
description = "Tear up the environment"
depends = ["build-bpf"]
run = "sudo ./scripts/tearup.sh"

[tasks.teardown]
alias = "tdn"
description = "Tear down the environment"
run = "sudo ./scripts/teardown.sh"

[tasks.replace]
alias = "rp"
description = "Replace the BPF program in ns3"
depends = ["build-bpf"]
run = "sudo ./scripts/replace.sh"
